runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:                                                                      
- name: jinja2                                                                  
  version: latest

env_variables:
  FIREBASE_PROJECT_ID: 'feelgood-58fe5'